services:
  - type: web
    name: hospital-management
    runtime: python
    buildCommand: ""
    startCommand: gunicorn myproject5.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject5.settings
      - key: PYTHON_VERSION
        value: 3.11.9
