# Generated by Django 5.0.4 on 2024-05-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_description',
            new_name='Dep_description',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='dep_name',
            new_name='Dep_name',
        ),
    ]
