# Generated by Django 5.0.4 on 2024-05-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0003_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='dep_name',
            new_name='Dep_name',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_image',
            new_name='Doc_image',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_name',
            new_name='Doc_name',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_spec',
            new_name='Doc_spec',
        ),
    ]
