# Generated by Django 5.0.4 on 2024-05-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0006_remove_booking_booked_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booked_on',
            field=models.DateField(auto_now=True),
        ),
    ]
