# Generated by Django 5.0.4 on 2024-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0007_booking_booked_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
