# Generated by Django 5.0.4 on 2024-05-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0008_add_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_patients',
            name='Age',
        ),
    ]
