# Generated by Django 5.0.4 on 2024-05-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0009_remove_add_patients_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_patients',
            name='Age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_patients',
            name='Age_unit',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
